config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get "/home", to: "pages#home"
  get "/dev", to: "pages#dev"
  get "/medbot", to: "pages#medbot"
  
  resources :machines
  
  resources :physicians do
    resources :addresses, module: :physicians, as: :addresses
    resources :phones, module: :physicians, as: :phones
    
    resources :prescriptions, except: [:destroy] do
      get 'search', on: :collection
    end
    member do
      get 'prescribe'
    end
  end
  resources :specialties

  resources :patients do
    resources :addresses, module: :patients, as: :addresses
    resources :phones, module: :patients, as: :phones

    resources :prescriptions, except: [:destroy] do
      get 'search', on: :collection
    end
    
    get 'search', on: :collection
    get 'autocomplete', on: :collection
  end
  
  resources :address_categories, except: [:show]
  resources :phone_categories, except: [:show]
  resources :prescription_categories, except: [:show]

end

app/models/prescription.rb
class Prescription < ActiveRecord::Base
  belongs_to :patient
  belongs_to :physician
  has_one :prescription_category, dependent: :destroy
  
  validates :physician_id, presence: true
  validates :patient_id, presence: true
  validates :clinical_information, presence: true, length: { minimum: 10 }
end

app/controllers/prescriptions_controller.rb
class PrescriptionsController < ApplicationController
  before_action :set_prescription, except: [:index, :new, :create]
  
  def index
    @physician = Physician.find(params[:physician_id])
    @prescriptions = @physician.prescriptions.paginate(page: params[:page], per_page: 3).order('updated_at DESC')
  end

  def new
    @physician = Physician.find(params[:physician_id])
    @prescription = Prescription.new
  end
  
  def create
    @physician = Physician.find(params[:physician_id])
    @prescription = @physician.prescriptions.new(prescription_params)
    
    if @prescription.save
      flash[:success] = "The prescription was created successfully!"
      redirect_to physician_prescription_path(@physician, @prescription)
    else
      render 'new'
    end
  end
  
  def show
    @physician = @prescription.physician
    @patient = @prescription.patient
  end
  
  def edit
    @physician = @prescription.physician
    @patient = @prescription.patient
  end
  
  def update
    @physician = Physician.find(params[:physician_id])
    
    if @prescription.update(prescription_params)
      flash[:success] = "The prescription was updated successfully!"
      redirect_to physician_prescription_path(@physician, @prescription)
    else
      render 'edit'
    end
  end
  
  def destroy
    @physician = @prescription.physician
    @prescription.destroy
    flash[:success] = "The prescription was deleted successfully!"
    redirect_to physician_path(@physician)
  end
  
  private
    def prescription_params
      params.require(:prescription).permit(:physician_id, :patient_id, :clinical_information, :status) #add specificities like claustrophobia, allergies, priority, range
    end
    
    def set_prescription
      @prescription = Prescription.find(params[:id])
    end
end

app/views/prescriptions/_form.html.erb
<%= render "shared/errors", obj: @prescription %>

<div class="row">
  <div class="well col-sm-4 col-sm-offset-2">
    <h2>Physician</h2>
    <div id="physicianinfo" class="col-sm-12">
      <div class="col-sm-4 imlbl">Name:</div>
      <div class="col-sm-8"><%= @physician.last_name + ', ' + @physician.first_name %></div>
      <div class="col-sm-4 imlbl">Permit number:</div>
      <div class="col-sm-8"><%= @physician.permit_number %></div>
    </div>
  </div>

  <div class="well col-sm-4">
    <h2>Patient</h2>
    <div id="patientsearch" class="col-sm-12">
      <%= text_field_tag :query, params[:query], id: 'patientsearchinput', class: 'form-control', placeholder: 'Patient\'s name or insurance number' %>
    </div>
    
    <div id="patientinfo" class="col-sm-12">
      <div class="col-sm-4 imlbl">Name:</div>
      <div class="col-sm-8" id="patientname"><%= @patient.last_name + ", " + @patient.first_name if @patient %></div>
      <div class="col-sm-4 imlbl">Insurance number:</div>
      <div class="col-sm-8" id="patientinsurancenumber"><%= @patient.insurance_number if @patient %></div>
      <input type="button" name="changepatient" id="changepatient" value="Change Patient" class="btn btn-success" />
    </div>
  </div>
</div>

<div class="row">
  <div class="well col-sm-8 col-sm-offset-2">
    <%= form_for [@physician, @prescription], html: { class: 'form-horizontal' } do |f| %>
      <%= f.hidden_field :physician_id, value: @physician.id %>
      <%= f.hidden_field :patient_id, value: @patient ? @patient.id : '' %>

      <div class="control-group">
        <div class="col-sm-4">
          <%= f.label :clinical_information, { class: 'control-label' } %>
        </div>
        <div class="col-sm-8">
          <%= f.text_area :clinical_information, { class: 'form-control' } %>
        </div>
      </div>
      <%= f.submit(@prescription.new_record? ? "Emit Prescription":"Update Prescription", class: "btn btn-success") %>
    <% end %>
  </div>
</div>

<%# content_for :head do %>
  <script type="text/javascript">
    $(document).on('page:change', function() {
      <% if @prescription.new_record? %>
      $('#patientsearch').show();
      $('#patientinfo').hide();
      <% else %>
      $('#patientsearch').hide();
      $('#patientinfo').show();
      <% end %>

      var kNoResults = "No patients found.";
      
      $("#patientsearchinput").autocomplete({
        minLength: 2,
        source: "/patients/autocomplete.json?term=" + $('#patientsearchinput').val(),
        select: function (event, suggestion) {
          if (suggestion.item.label === kNoResults) {
            event.preventDefault();
          }
          else {
            onSelectPatient(event, suggestion);
          }
        },
        focus: function (event, suggestion) {
          if (suggestion.item.label === kNoResults) {
            event.preventDefault();
          }
        },
        response: function (event, suggestions) {
          if (suggestions.content.length === 0) {
            var noResult = { value: event.target.value, label: kNoResults };
            suggestions.content.push(noResult);
          }
          else {
            // Autocomplete needs variables named 'label' and 'value' to display suggestions properly, we add them here
            $.each(suggestions.content, function (i, obj) {
              obj.label = obj.last_name + ', ' + obj.first_name + ' (' + obj.insurance_number + ')'; // whatever appears in the suggestions box
              obj.value = obj.last_name + ', ' + obj.first_name + ' (' + obj.insurance_number + ')'; // whatever appears in the input field
            });
          }
        }
      });
      
      function onSelectPatient(event, suggestion) {
        $('#prescription_patient_id').val(suggestion.item.id);
        $('#patientsearch').hide();
        $('#patientname').html(suggestion.item.last_name + ', ' + suggestion.item.first_name);
        $('#patientinsurancenumber').html(suggestion.item.insurance_number);
        $('#patientinfo').show();
      }
      
      function changePatientSearch() {
        $('prescriptionpatientid').val('');
        $('#patientinfo').hide();
        $('#patientsearchinput').val('');
        $('#patientsearch').show();
        $('#patientsearchinput').focus();
      }
    
      $('#changepatient').click(changePatientSearch);
    });
  </script>
<%# end %>

app/views/prescriptions/_form.js.erb
$(document).on('page:load', function() {

  alert('MORMAMMOAMA');

  <% if @prescription.new_record? %>
  $('#patientsearch').show();
  $('#patientinfo').hide();
  <% else %>
  $('#patientsearch').hide();
  $('#patientinfo').show();
  <% end %>

  var kNoResults = "No patients found.";
  
  $("#patientsearchinput").autocomplete({
    minLength: 2,
    source: "/patients/autocomplete.json?term=" + $('#patientsearchinput').val(),
    select: function (event, suggestion) {
      if (suggestion.item.label === kNoResults) {
        event.preventDefault();
      }
      else {
        onSelectPatient(event, suggestion);
      }
    },
    focus: function (event, suggestion) {
      if (suggestion.item.label === kNoResults) {
        event.preventDefault();
      }
    },
    response: function (event, suggestions) {
      if (suggestions.content.length === 0) {
        var noResult = { value: event.target.value, label: kNoResults };
        suggestions.content.push(noResult);
      }
      else {
        // Autocomplete needs variables named 'label' and 'value' to display suggestions properly, we add them here
        $.each(suggestions.content, function (i, obj) {
          obj.label = obj.last_name + ', ' + obj.first_name + ' (' + obj.insurance_number + ')'; // whatever appears in the suggestions box
          obj.value = obj.last_name + ', ' + obj.first_name + ' (' + obj.insurance_number + ')'; // whatever appears in the input field
        });
      }
    }
  });
  
  function onSelectPatient(event, suggestion) {
    $('#prescription_patient_id').val(suggestion.item.id);
    $('#patientsearch').hide();
    $('#patientname').html(suggestion.item.last_name + ', ' + suggestion.item.first_name);
    $('#patientinsurancenumber').html(suggestion.item.insurance_number);
    $('#patientinfo').show();
  }
  
  function changePatientSearch() {
    $('prescriptionpatientid').val('');
    $('#patientinfo').hide();
    $('#patientsearchinput').val('');
    $('#patientsearch').show();
    $('#patientsearchinput').focus();
  }

  $('#changepatient').click(changePatientSearch);
});

app/views/prescriptions/_prescription.erb
<div class="row">
  <div class="col-sm-offset-2 col-sm-8 well">
    <div class="inline">
      Patient: <%= link_to prescription.patient.last_name + ', ' + prescription.patient.first_name + ' (' + prescription.patient.insurance_number + ')', patient_path(prescription.patient) %><br />
      Prescribed by: <%= link_to prescription.physician.last_name + ', ' + prescription.physician.first_name + ' (' + prescription.physician.permit_number + ')', physician_path(prescription.physician) %><br />
      Last updated: <%= time_ago_in_words(prescription.updated_at) %> ago - Emitted: <%= time_ago_in_words(prescription.created_at) %> ago<br />
    </div>
    <div class="inline pull-right">
      <%= link_to physician_prescription_path(prescription.physician, prescription), class: "btn btn-success" do %>
        <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
      <% end %>
      <%= link_to edit_physician_prescription_path(prescription.physician, prescription), class: "btn btn-warning" do %>
        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
      <% end %>
    </div>
  </div>
</div>

app/views/prescriptions/_prescriptions.erb
<% prescriptions.each do |p| %>
  <%= render partial: 'prescriptions/prescription', locals: { prescription: p } %>
<% end %>

app/views/prescriptions/edit.html.erb
<%= render 'shared/page_title', title: 'Edit prescription' %>
<%= render 'form' %>
<%= link_to 'Return without saving', physician_path(@physician), class: 'btn btn-warning' %>

app/views/prescriptions/index.html.erb
<%= render 'shared/page_title', title: 'Prescriptions' %>

<div id="prescriptions">
  <%= render @prescriptions %>
</div>

<%= will_paginate @prescriptions %>

app/views/prescriptions/index.js.erb
$('#prescriptions').append('<%= j render(@prescriptions) %>');
$('div.pagination').replaceWith('<%= j will_paginate(@prescriptions) if @prescriptions.next_page %>');

app/views/prescriptions/new.html.erb
<%= render 'shared/page_title', title: 'New prescription' %>
<%= render 'form' %>
<%= link_to 'Return without saving', physician_path(@physician), class: 'btn btn-warning' %>

app/views/prescriptions/show.html.erb
<%= render 'shared/page_title', title: 'Prescription' %>

<div class="row">
  <div class="well col-sm-4 col-sm-offset-2">
    <h2>Physician</h2>
    <div id="physicianinfo" class="col-sm-12">
      <div class="col-sm-4 imlbl">Name:</div>
      <div class="col-sm-8"><%= @physician.last_name + ', ' + @physician.first_name %></div>
      <div class="col-sm-4 imlbl">Permit number:</div>
      <div class="col-sm-8"><%= @physician.permit_number %></div>
    </div>
  </div>

  <div class="well col-sm-4">
    <h2>Patient</h2>
    <div id="patientinfo" class="col-sm-12">
      <div class="col-sm-4 imlbl">Name:</div>
      <div class="col-sm-8" id="patientname"><%= @patient.last_name + ", " + @patient.first_name if @patient %></div>
      <div class="col-sm-4 imlbl">Insurance number:</div>
      <div class="col-sm-8" id="patientinsurancenumber"><%= @patient.insurance_number if @patient %></div>
    </div>
  </div>
</div>

<div class="row">
  <div class="well col-sm-8 col-sm-offset-2">
    <h2>Clinical information</h2>
    <%= @prescription.clinical_information %>
  </div>
</div>

<%= link_to "Return to physician's page", physician_path(@physician), class: 'btn btn-success' %>
<%= link_to "Return to patient's page", patient_path(@patient), class: 'btn btn-success' %>