config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get "/home", to: "pages#home"
  get "/dev", to: "pages#dev"
  get "/medbot", to: "pages#medbot"
  
  resources :machines
  
  resources :physicians do
    resources :addresses, module: :physicians, as: :addresses
    resources :phones, module: :physicians, as: :phones
    
    resources :prescriptions, except: [:destroy] do
      get 'search', on: :collection
    end
    member do
      get 'prescribe'
    end
  end
  resources :specialties

  resources :patients do
    resources :addresses, module: :patients, as: :addresses
    resources :phones, module: :patients, as: :phones

    resources :prescriptions, except: [:destroy] do
      get 'search', on: :collection
    end
    
    get 'search', on: :collection
    get 'autocomplete', on: :collection
  end
  
  resources :address_categories, except: [:show]
  resources :phone_categories, except: [:show]
  resources :prescription_categories, except: [:show]

end

app/models/prescription_category.rb
class PrescriptionCategory < ActiveRecord::Base
  belongs_to :prescription
end

app/controllers/prescription_categories_controller.rb
class PrescriptionCategoriesController < ApplicationController
  before_action :set_prescription_category, except: [:index, :new, :create]
  
  def index
    @prescription_categories = PrescriptionCategory.all
  end
  
  def new
    @prescription_category = PrescriptionCategory.new
  end
  
  def create
    @prescription_category = PrescriptionCategory.new(prescription_category_params)
    
    if @prescription_category.save
      flash[:success] = "The prescription category was created successfully!"
      redirect_to prescription_categories_path
    else
      render 'new'
    end
  end
  
  def show
  end
  
  def edit
  end
  
  def update
    if @prescription_category.update(prescription_category_params)
      flash[:success] = "The prescription category was updated successfully!"
      redirect_to prescription_categories_path
    else
      render 'edit'
    end
  end
  
  def destroy
    @prescription_category.destroy
    flash[:success] = "The prescription category was deleted successfully!"
    redirect_to prescription_categories_path
  end
  
  private
    def prescription_category_params
      params.require(:prescription_category).permit(:name)
    end
    
    def set_prescription_category
      @prescription_category = PrescriptionCategory.find(params[:id])
    end
end

app/views/prescription_categories/_form.html.erb
<%= render "shared/errors", obj: @prescription_category %>

<div class="row">
  <div class="well col-sm-8 col-sm-offset-2">
    <%= form_for @prescription_category, html: { class: 'form-horizontal' } do |f| %>
      <div class="control-group">
        <div class="col-sm-4">
          <%= f.label :name, { class: 'control-label' } %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :name, { class: 'form-control', :autofocus => true } %>
        </div>
      </div>
      <%= f.submit(@prescription_category.new_record? ? "Create Prescription Category":"Update Prescription Category", class: "btn btn-success") %>
    <% end %>
  </div>
</div>

app/views/prescription_categories/edit.html.erb
<%= render 'shared/page_title', title: 'Edit Prescription Category' %>
<%= render 'form' %>
<%= link_to 'Return without saving', prescription_categories_path, class: 'btn btn-warning' %>

app/views/prescription_categories/index.html.erb
<%= render 'shared/page_title', title: 'Prescription Categories' %>

<div class="row">
  <div class="col-sm-12">
    <br />
    <%= link_to "Add Category", new_prescription_category_path, class: "btn btn-success" %></p>
  </div>
</div>
  
<% @prescription_categories.each do |category| %>
  <div class="row">
    <div class="well col-sm-8 col-sm-offset-2">
      <div class="col-sm-11">
        <%= category.name %>
      </div>
      <div class="col-sm-1">
        <%= link_to edit_prescription_category_path(category), class: "btn btn-warning" do %>
          <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/prescription_categories/new.html.erb
<%= render 'shared/page_title', title: 'New Prescription Category' %>
<%= render 'form' %>
<%= link_to 'Return without saving', prescription_categories_path, class: 'btn btn-warning' %>