config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get "/home", to: "pages#home"
  get "/dev", to: "pages#dev"
  get "/medbot", to: "pages#medbot"
  
  resources :machines
  
  resources :physicians do
    resources :addresses, module: :physicians, as: :addresses
    resources :phones, module: :physicians, as: :phones
    
    resources :prescriptions, except: [:destroy] do
      get 'search', on: :collection
    end
    member do
      get 'prescribe'
    end
  end
  resources :specialties

  resources :patients do
    resources :addresses, module: :patients, as: :addresses
    resources :phones, module: :patients, as: :phones

    resources :prescriptions, except: [:destroy] do
      get 'search', on: :collection
    end
    
    get 'search', on: :collection
    get 'autocomplete', on: :collection
  end
  
  resources :address_categories, except: [:show]
  resources :phone_categories, except: [:show]
  resources :prescription_categories, except: [:show]

end

app/models/physician.rb
class Physician < ActiveRecord::Base
  has_many :prescriptions
  has_many :patients, through: :prescriptions
  has_many :physician_specialties, dependent: :destroy
  has_many :specialties, through: :physician_specialties
  has_many :addresses, as: :addressable, dependent: :destroy
  has_many :phones, as: :phonable, dependent: :destroy
end

app/controllers/physicians/addresses_controller.rb
class Physicians::AddressesController < AddressesController
  before_action :set_addressable
  
  private
    def set_addressable
      @addressable = Physician.find(params[:physician_id])
    end
end

app/controllers/physicians/phones_controller.rb
class Physicians::PhonesController < PhonesController
  before_action :set_phonable
  
  private
    def set_phonable
      @phonable = Physician.find(params[:physician_id])
    end
end

app/controllers/physicians_controller.rb
class PhysiciansController < ApplicationController
  before_action :set_physician, :only => [:show, :edit, :update, :destroy, :prescribe]
    
  def index
    @physicians = Physician.paginate(page: params[:page], per_page: 15).order('last_name ASC')
  end

  def new
    @physician = Physician.new
    @specialties = Specialty.all.order('name ASC')
  end
  
  def create
    @physician = Physician.new(physician_params)
    
    if @physician.save
      flash[:success] = "The physician profile was created successfully!"
      redirect_to physician_path(@physician)
    else
      render 'new'
    end
  end
  
  def show
    @specialties = @physician.specialties.order('name ASC')
    @prescriptions = @physician.prescriptions.paginate(page: params[:page], per_page: 3).order('updated_at DESC')
  end
  
  def edit
    @specialties = Specialty.all.order('name ASC')
  end
  
  def update
    if @physician.update(physician_params)
      flash[:success] = "The physician profile was updated successfully!"
      redirect_to physician_path(@physician)
    else
      render 'edit'
    end
  end
  
  def destroy
    @physician.destroy
    flash[:success] = "The physician profile was deleted successfully!"
    redirect_to physicians_path
  end
  
  def prescribe
    @prescription = @physician.prescriptions.new
  end
  
  private
    def physician_params
      params.require(:physician).permit(:first_name, :last_name, :middle_name, :gender, :permit_number, specialty_ids: [])
      #genre, numéro de permis, type de permis, statut, spécialités, activités, habilitations, adresse
    end
    
    def set_physician
      @physician = Physician.find(params[:id])
    end
end

app/views/physicians/_form.html.erb
<%= render "shared/errors", obj: @physician %>

<div class="row">
  <div class="well col-sm-8 col-sm-offset-2">
    <%= form_for @physician, html: { class: 'form-horizontal' } do |f| %>
      <div class="control-group">
        <div class="col-sm-4">
          <%= f.label :first_name, { class: 'control-label' } %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :first_name, { class: 'form-control', :autofocus => true } %>
        </div>
      </div>
      <div class="control-group">
        <div class="col-sm-4">
          <%= f.label :last_name, { class: 'control-label' } %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :last_name, { class: 'form-control' } %>
        </div>
      </div>
      <div class="control-group">
        <div class="col-sm-4">
          <%= f.label :middle_name, { class: 'control-label' } %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :middle_name, { class: 'form-control' } %>
        </div>
      </div>
      <div class="control-group">
        <div class="col-sm-4">
          <%= f.label :gender, { class: 'control-label' } %>
        </div>
        <div class="col-sm-8">
          <%= f.select :gender, options_for_select([['Female','F'],['Male','M']], @physician.gender), {}, { class: 'form-control' } %>
        </div>
      </div>
      <div class="control-group">
        <div class="col-sm-4">
          <%= f.label :permit_number, { class: 'control-label' } %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :permit_number, { class: 'form-control' } %>
        </div>
      </div>
      <div class="control-group">
        <div class="col-sm-4">
          <%= f.label :specialty_ids, { class: 'control-label' } %>
        </div>
        <div class="col-sm-8">
          <%= f.select :specialty_ids, @specialties.collect {|s| [s.name, s.id]}, {}, { :multiple => true, class: "form-control" } %>
          <p>(Hold CTRL or CMD and click for several specialties)</p>
        </div>
      </div>
      <%= f.submit(@physician.new_record? ? "Create Physician Profile":"Update Physician Profile", class: "btn btn-success") %>
    <% end %>
  </div>
</div>

app/views/physicians/_physician.html.erb
<div class="physician row">
  <div class="well col-sm-offset-2 col-sm-8">
    <%= link_to physician.last_name + ', ' + physician.first_name + ' (' + physician.permit_number + ')', physician_path(physician) %>
  </div>
</div>

app/views/physicians/edit.html.erb
<%= render 'shared/page_title', title: 'Edit Physician Profile' %>
<%= render 'form' %>
<%= link_to 'Return without saving', physician_path(@physician), class: 'btn btn-warning' %>

app/views/physicians/index.html.erb
<%= render 'shared/page_title', title: 'Physicians' %>

<div id="physicians">
  <%= render @physicians %>
</div>

<%= will_paginate @physicians %>

app/views/physicians/index.js.erb
$('#physicians').append('<%= j render(@physicians) %>');
$('div.pagination').replaceWith('<%= j will_paginate(@physicians) if @physicians.next_page %>');

app/views/physicians/new.html.erb
<%= render 'shared/page_title', title: 'New Physician Profile' %>
<%= render 'form' %>
<%= link_to 'Return without saving', physician_path(@physician), class: 'btn btn-warning' %>

app/views/physicians/show.html.erb
<%= render 'shared/page_title', title: @physician.last_name + ', ' + @physician.first_name + ' ' + @physician.middle_name + ' (' + @physician.permit_number + ')' %>

<div class="row">
  <div class="well col-sm-offset-2 col-sm-8">
    
    <!-- Identification -->
    <div class="row">
      <div class="col-xs-11">
        
        <div class="row">
          <div class="col-sm-6 imlbl">
            Name:
          </div>
          <div class="col-sm-6">
            <%= @physician.last_name + ', ' + @physician.first_name + ' ' + @physician.middle_name %>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-6 imlbl">
            Permit Number:
          </div>
          <div class="col-sm-6">
            <%= @physician.permit_number %>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-6 imlbl">
            Gender:
          </div>
          <div class="col-sm-6">
            <%= @physician.gender %>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-6 imlbl">
            Specialties:
          </div>
          <div class="col-sm-6">
            <% @specialties.each do |s| %>
              <div><%= s.name %></div>
            <% end %>
          </div>
        </div>
        
      </div>
      <div class="col-xs-1">
        
        <%= link_to edit_physician_path(@physician), class: "btn btn-warning" do %>
          <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
        <% end %>
        
      </div>

    </div>
    
    <br />

    <!-- Contact Info -->
    <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
      <div class="panel panel-default">
        <div class="panel-heading" role="tab" id="headingOne" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">

          <h4 class="panel-title">Contact Information <i class="indicator glyphicon glyphicon-chevron-down pull-right"></i></h4>

        </div>
        <div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne">
          <div class="panel-body">
            
            <div>
              <h5>Addresses</h5>
            </div>
            <div>
              <%= render partial: 'addresses/addresses', locals: { addressable: @physician } %>
            </div>
            <div>
              <%= link_to 'Add Address', new_physician_address_path(@physician), class: 'btn btn-success' %>
            </div>

            <br />

            <div>
              <h5>Phone numbers</h5>
            </div>
            <div>
              <%= render partial: 'phones/phones', locals: { phonable: @physician } %>
            </div>
            <div>
              <%= link_to 'Add Phone Number', new_physician_phone_path(@physician), class: 'btn btn-success' %>
            </div>
            
          </div>
        </div>
      </div>
    </div>
    
  </div>
</div>

<div>
  <%= link_to 'Prescribe', new_physician_prescription_path(@physician), class: 'btn btn-success' %>
  <!-- Prescriptions follow up -->
  <div>
    <h4>Prescriptions</h4>
  </div>
  <div>
    <h5>Actives</h5>
  </div>
  <%= render @prescriptions %>
  <div>
    <h5>Completed or cancelled</h5>
  </div>
  
</div>

<% content_for :head do %>
  <script type="text/javascript">
    $(document).on('page:change', function() {
      $('#accordion').on('hidden.bs.collapse', toggleChevron);
      $('#accordion').on('shown.bs.collapse', toggleChevron);
    });
  </script>
<% end %>