config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get "/home", to: "pages#home"
  get "/dev", to: "pages#dev"
  get "/medbot", to: "pages#medbot"
  
  resources :machines
  
  resources :physicians do
    resources :addresses, module: :physicians, as: :addresses
    resources :phones, module: :physicians, as: :phones
    
    resources :prescriptions, except: [:destroy] do
      get 'search', on: :collection
    end
    member do
      get 'prescribe'
    end
  end
  resources :specialties

  resources :patients do
    resources :addresses, module: :patients, as: :addresses
    resources :phones, module: :patients, as: :phones

    resources :prescriptions, except: [:destroy] do
      get 'search', on: :collection
    end
    
    get 'search', on: :collection
    get 'autocomplete', on: :collection
  end
  
  resources :address_categories, except: [:show]
  resources :phone_categories, except: [:show]
  resources :prescription_categories, except: [:show]

end

app/views/pages/dev.html.erb
<div class="row">
  <div class="well col-sm-12">
    <%= link_to 'Create physician', new_physician_path %><br />
  </div>
</div>

<div class="row">
  <div class="well col-sm-12">
    <%= link_to 'Create machine', new_machine_path %><br />
  </div>
</div>

app/views/pages/home.html.erb
<div class="jumbotron center">
  <h1>Welcome to the Imagine medical imaging booking platform.</h1>
  <h2>The purpose of this tool is to centralize your access to medical imaging after receiving a prescription from your physician or specialist.</h2>
  
  <%= link_to "Book now!", '', class: "btn btn-lg btn-danger" %>
</div>

<div class="row">
  <div class="col-sm-6 roundbox">
    <center>
      <h3 class="midrow">Log in as Physician</h3>
      <i class="fa fa-user-md fa-6"></i>
      <h2>Prescribe imaging services to your patients</h2>
      <p><%= link_to "Sign in as Physician", physicians_path, class: "btn btn-warning btn-small" %></p>
    </center>
  </div>
  <div class="col-sm-6 roundbox">
    <center>
      <h3 class="midrow">Log in as Patient</h3>
      <i class="fa fa-user fa-6"></i>
      <h2>View your prescriptions and define the acceptable travel range to fulfill them</h2>
      <p><%= link_to "Sign in as Patient", patients_path, class: "btn btn-warning btn-small" %></p>
    </center>
  </div>
</div>

<div class="row">
  <div class="col-sm-6 col-sm-offset-3 roundbox">
    <center>
      <h3 class="midrow">View imaging service providers</h3>
      <i class="fa fa-hospital-o fa-6"></i>
      <h2>Browse and view imaging service providers in your area</h2>
      <p><%= link_to "Browse medical imaging service providers", '', class: "btn btn-warning btn-small" %></p>
    </center>
  </div>
</div>